language: node_js

sudo: false

node_js:
  - '8'

branches:
  only:
  - master

# cache:
#   directories:
#     - node_modules

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy